jit.opt.start(2)

include("includes/console_colors.lua")
include("includes/hook.lua")
include("includes/util.lua")
include("includes/statuscodes.lua")
include("includes/extensions/math.lua")
include("includes/extensions/string.lua")
include("includes/extensions/table.lua")
include("includes/extensions/debug.lua")
include("includes/modules/module.lua")
include("includes/modules/pon.lua")

include("luna/luna.lua")
include("test.lun")